### ISSUE TITLE
Can't resolve tslib

### ISSUE THREAD

**Issue by utrolig** [jeffijoe/streamsource#34]
When building my app for production I get an error with regards to tslib not being installed. 

Maybe a missing peer dependency?

**Comment by jeffijoe** [comment]
How are you building it? I haven’t had this issue using just tsc or babel

**Comment by utrolig** [comment]
I'm just using `tsc` to build from typescript to ES2021.

**Comment by utrolig** [comment]
Seems like it was an issue with my docker builds, not getting the error anymore.
